name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: npm run build

      - name: Deploy to GitHub Pages
        run: |
          git config user.name ${{ secrets.GITHUB_USER }}
          git config user.email ${{ secrets.GITHUB_EMAIL }}
          git checkout --orphan gh-pages
          git --work-tree build add --all
          git --work-tree build commit -m "GitHub Pages Deployment"
          git push origin HEAD:gh-pages --force
        env:
          GITHUB_USER: ${{ secrets.GITHUB_USER }}
          GITHUB_EMAIL: ${{ secrets.GITHUB_EMAIL }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
